'''
Python regression function module generated by Evogression
'''

def regression(parameters: dict) -> float:
    '''
    Function for predicting 'inj_diff'
    Generated from an Evogression Creature
    '''

    # Standardize input data
    data = {}
    for param, value in parameters.items():
        if param == 'DELTA_Avg_CCS1_DH6325Ps_psi':
            data['DELTA_Avg_CCS1_DH6325Ps_psi'] = (value - 0.17045) / 55.56611
        if param == 'DELTA_Avg_PLT_CO2VentRate_TPH':
            data['DELTA_Avg_PLT_CO2VentRate_TPH'] = (value - -0.00616) / 1.36001
        if param == 'DELTA_Avg_CCS1_WHCO2InjTp_F':
            data['DELTA_Avg_CCS1_WHCO2InjTp_F'] = (value - 0.05171) / 32.37261
        if param == 'DELTA_Avg_CCS1_DH6325Tp_F':
            data['DELTA_Avg_CCS1_DH6325Tp_F'] = (value - 0.01025) / 2.08213

    T = 0

    # LAYER_1
    T += 0.1283
    T += 0.1125 * data['DELTA_Avg_CCS1_WHCO2InjTp_F'] + -0.0206
    T += -2.3283 * data['DELTA_Avg_CCS1_DH6325Tp_F'] + -0.0597
    T += -0.1100 * data['DELTA_Avg_PLT_CO2VentRate_TPH'] + -0.0329
    T += 2.4617 * data['DELTA_Avg_CCS1_DH6325Ps_psi'] + -0.0162

    # Unstandardize result
    T = T * 4.06880 + 0.00140

    return T
